.TH CMIX 1 "January 2026" "1.9" "Cmix Manual"
.SH NAME
cmix \- World-record-holding compression algorithm
.SH SYNOPSIS
.B cmix
[\fI-options\fR] \fIinput\fR \fIoutput\fR
.SH DESCRIPTION
.B cmix
is an ultra-high-pressure compression tool using context mixing and neural networks.
It is designed for maximum compression ratio at the cost of high CPU and RAM usage.
.SH OPTIONS
.TP
.B \-c
Compress the input file.
.TP
.B \-d
Decompress the input file.
.SH AUTHOR
Byron Knoll. Homebrew formula by Aritya Arjunan.
